version: '3'

services:
  node1:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "5049:5049"
    networks:
      - dapp-network
  node2:
    build:
      dockerfile: Dockerfile
      context: .
    networks:
      - dapp-network
  node3:
    build:
      dockerfile: Dockerfile
      context: .
    networks:
      - dapp-network
  
networks:
  dapp-network:
    driver: bridge
    ipam:
        driver: default
        config:
            - subnet: "10.10.0.0/24"
